# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semanticcheck',
            options={'ordering': ['label'], 'verbose_name': 'Semantic check', 'verbose_name_plural': 'Semantic checks'},
        ),
        migrations.RemoveField(
            model_name='semanticcheck',
            name='value',
        ),
    ]
