# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0002_auto_20170723_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotationsemanticcheck',
            options={'ordering': ['-value'], 'verbose_name': 'Annotation semantic check', 'verbose_name_plural': 'Annotation semantic checks'},
        ),
        migrations.AlterField(
            model_name='annotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='flickr.Image'),
        ),
    ]
