# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0002_annotation_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'get_latest_by': 'updated_at', 'ordering': ['-is_approved', '-created_at', '-updated_at'], 'verbose_name': 'Annotation', 'verbose_name_plural': 'Annotations'},
        ),
    ]
