# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0002_auto_20170729_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markedobject',
            name='guid',
        ),
    ]
