# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0003_remove_markedobject_guid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markedobject',
            name='annotation',
        ),
        migrations.AddField(
            model_name='annotation',
            name='marked_objects',
            field=models.ManyToManyField(to='flickr.MarkedObject'),
        ),
    ]
