# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0003_auto_20170730_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotationsemanticcheck',
            options={'ordering': ['-value'], 'verbose_name': 'Annotation semantic check', 'verbose_name_plural': 'Annotation semantic checks'},
        ),
    ]
