# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0004_auto_20170724_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='semantic_check_values',
            new_name='semantic_checks',
        ),
    ]
