# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0005_auto_20170727_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semanticcheck',
            options={'ordering': ['id'], 'verbose_name': 'Semantic check', 'verbose_name_plural': 'Semantic checks'},
        ),
        migrations.AlterField(
            model_name='annotationsemanticcheck',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
