# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0006_auto_20170719_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='state',
            field=models.IntegerField(choices=[(0, 'Selected'), (1, 'Annotated'), (2, 'Approved'), (3, 'Discarded')], default=0),
        ),
    ]
