# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0006_auto_20170727_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semantic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Semantic check',
                'verbose_name_plural': 'Semantic checks',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='annotationsemanticcheck',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='annotationsemanticcheck',
            name='semantic_check',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='semantic_checks',
        ),
        migrations.DeleteModel(
            name='AnnotationSemanticCheck',
        ),
        migrations.DeleteModel(
            name='SemanticCheck',
        ),
        migrations.AddField(
            model_name='semantic',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flickr.Annotation'),
        ),
    ]
