# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0006_auto_20170807_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markedobject',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='uuid'),
        ),
    ]
