# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0007_auto_20170728_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semantic',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_checks', to='flickr.Annotation'),
        ),
    ]
