# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0007_auto_20170720_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscardedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='image',
            name='license',
            field=models.CharField(blank=True, choices=[(0, 'All Rights Reserved'), (1, 'Attribution-NonCommercial-ShareAlike License'), (2, 'Attribution-NonCommercial License'), (3, 'Attribution-NonCommercial-NoDerivs License'), (4, 'Attribution License'), (5, 'Attribution-ShareAlike License'), (6, 'Attribution-NoDerivs License'), (7, 'No known copyright restrictions'), (8, 'United States Government Work')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='licenses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'All Rights Reserved'), (1, 'Attribution-NonCommercial-ShareAlike License'), (2, 'Attribution-NonCommercial License'), (3, 'Attribution-NonCommercial-NoDerivs License'), (4, 'Attribution License'), (5, 'Attribution-ShareAlike License'), (6, 'Attribution-NoDerivs License'), (7, 'No known copyright restrictions'), (8, 'United States Government Work')], max_length=20),
        ),
    ]
