# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 19:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0008_auto_20170720_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discardedimage',
            options={'verbose_name': 'Discarded image', 'verbose_name_plural': 'Discarded images'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='state',
        ),
        migrations.AddField(
            model_name='discardedimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 20, 18, 56, 38, 758282, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discardedimage',
            name='farm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discardedimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='flickr_images'),
        ),
        migrations.AddField(
            model_name='discardedimage',
            name='isfamily',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='discardedimage',
            name='isfriend',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='discardedimage',
            name='ispublic',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='discardedimage',
            name='license',
            field=models.CharField(blank=True, choices=[(0, 'All Rights Reserved'), (1, 'Attribution-NonCommercial-ShareAlike License'), (2, 'Attribution-NonCommercial License'), (3, 'Attribution-NonCommercial-NoDerivs License'), (4, 'Attribution License'), (5, 'Attribution-ShareAlike License'), (6, 'Attribution-NoDerivs License'), (7, 'No known copyright restrictions'), (8, 'United States Government Work')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='discardedimage',
            name='owner',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discardedimage',
            name='secret',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discardedimage',
            name='server',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discardedimage',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discardedimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discardedimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discardedimage',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
