# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0008_auto_20170728_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationSemanticCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flickr.Annotation')),
            ],
            options={
                'verbose_name': 'Annotation semantic check',
                'verbose_name_plural': 'Annotation semantic checks',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='SemanticCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Semantic check',
                'verbose_name_plural': 'Semantic checks',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='semantic',
            name='annotation',
        ),
        migrations.DeleteModel(
            name='Semantic',
        ),
        migrations.AddField(
            model_name='annotationsemanticcheck',
            name='semantic_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flickr.SemanticCheck'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='semantic_checks',
            field=models.ManyToManyField(through='flickr.AnnotationSemanticCheck', to='flickr.SemanticCheck'),
        ),
    ]
