# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0009_auto_20170720_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Selected image', 'verbose_name_plural': 'Selected images'},
        ),
        migrations.RemoveField(
            model_name='discardedimage',
            name='image',
        ),
    ]
