# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0009_auto_20170728_0051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotationsemanticcheck',
            unique_together=set([('annotation', 'semantic_check')]),
        ),
    ]
