# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0010_auto_20170728_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.IntegerField(choices=[(0, 'Face'), (1, 'Genital'), (2, 'Buttock'), (3, 'Breast'), (4, 'Foot'), (5, 'Hand'), (6, 'Arm')])),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Female')], null=True)),
                ('age_group', models.IntegerField(blank=True, choices=[(0, 'Child'), (1, 'Teen'), (2, 'Adult'), (3, 'Elder')], null=True)),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Objects',
                'ordering': ['-object_type', '-age_group', '-gender'],
            },
        ),
        migrations.CreateModel(
            name='ObjectXRectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Object rectangle',
                'verbose_name_plural': 'Object rectangles',
                'ordering': [],
            },
        ),
        migrations.AddField(
            model_name='objectx',
            name='rectangle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flickr.ObjectXRectangle'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='objects',
            field=models.ManyToManyField(blank=True, null=True, to='flickr.ObjectX'),
        ),
    ]
