# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 15:17
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0010_auto_20170721_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='flickr_images', verbose_name='Locally saved image'),
        ),
    ]
