# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0011_auto_20170721_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
