# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0012_remove_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='skin_pixels_image',
            new_name='paint_image',
        ),
    ]
