# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0012_auto_20170729_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='objects',
            new_name='marked_objects',
        ),
    ]
