# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0013_auto_20170723_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='flickr.Image'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='paint_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='paint_image'),
        ),
    ]
