# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0013_auto_20170729_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectx',
            options={'ordering': ['-object_type', '-age_group', '-gender'], 'verbose_name': 'Marked Object', 'verbose_name_plural': 'Marked objects'},
        ),
        migrations.RemoveField(
            model_name='objectx',
            name='rectangle',
        ),
        migrations.AddField(
            model_name='objectxrectangle',
            name='object_x',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flickr.ObjectX'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objectx',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')], null=True),
        ),
    ]
