# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0014_auto_20170729_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.IntegerField(choices=[(0, 'Face'), (1, 'Genital'), (2, 'Buttock'), (3, 'Breast'), (4, 'Foot'), (5, 'Hand'), (6, 'Arm')])),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')], null=True)),
                ('age_group', models.IntegerField(blank=True, choices=[(0, 'Child'), (1, 'Teen'), (2, 'Adult'), (3, 'Elder')], null=True)),
            ],
            options={
                'verbose_name': 'Marked Object',
                'verbose_name_plural': 'Marked objects',
                'ordering': ['-object_type', '-age_group', '-gender'],
            },
        ),
        migrations.RenameModel(
            old_name='ObjectXRectangle',
            new_name='MarkedObjectRectangle',
        ),
        migrations.AlterModelOptions(
            name='markedobjectrectangle',
            options={'ordering': [], 'verbose_name': 'Rectangle', 'verbose_name_plural': 'Rectangles'},
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='marked_objects',
        ),
        migrations.AlterField(
            model_name='markedobjectrectangle',
            name='object_x',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flickr.MarkedObject'),
        ),
        migrations.DeleteModel(
            name='ObjectX',
        ),
        migrations.AddField(
            model_name='markedobject',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flickr.Annotation'),
        ),
    ]
