# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0015_auto_20170729_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationMarkedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flickr.Annotation')),
            ],
            options={
                'verbose_name': 'Annotation marked object',
                'verbose_name_plural': 'Annotation marked objects',
                'ordering': [],
            },
        ),
        migrations.RemoveField(
            model_name='markedobjectrectangle',
            name='object_x',
        ),
        migrations.RemoveField(
            model_name='markedobject',
            name='annotation',
        ),
        migrations.DeleteModel(
            name='MarkedObjectRectangle',
        ),
        migrations.AddField(
            model_name='annotationmarkedobject',
            name='marked_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flickr.MarkedObject'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='marked_objects',
            field=models.ManyToManyField(through='flickr.AnnotationMarkedObject', to='flickr.MarkedObject'),
        ),
        migrations.AlterUniqueTogether(
            name='annotationmarkedobject',
            unique_together=set([('annotation', 'marked_object')]),
        ),
    ]
