# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0016_auto_20170729_2020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotationmarkedobject',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='annotationmarkedobject',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='annotationmarkedobject',
            name='marked_object',
        ),
        migrations.AlterModelOptions(
            name='markedobject',
            options={'ordering': [], 'verbose_name': 'Annotation marked object', 'verbose_name_plural': 'Annotation marked objects'},
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='marked_objects',
        ),
        migrations.AddField(
            model_name='markedobject',
            name='annotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flickr.Annotation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markedobject',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markedobject',
            name='width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markedobject',
            name='x',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markedobject',
            name='y',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnnotationMarkedObject',
        ),
    ]
