# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0017_auto_20170729_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotationsemanticcheck',
            options={'ordering': ['-value'], 'verbose_name': 'Semantic check', 'verbose_name_plural': 'Semantic checks'},
        ),
        migrations.AlterModelOptions(
            name='markedobject',
            options={'ordering': [], 'verbose_name': 'Marked object', 'verbose_name_plural': 'Marked objects'},
        ),
        migrations.AlterField(
            model_name='markedobject',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_objects', to='flickr.Annotation'),
        ),
        migrations.AlterField(
            model_name='markedobject',
            name='object_type',
            field=models.IntegerField(choices=[(0, 'Face'), (1, 'Genital'), (2, 'Buttock'), (3, 'Breast'), (4, 'Foot'), (5, 'Hand'), (6, 'Arm')], verbose_name='Type'),
        ),
    ]
