branch-defaults:
  master:
    environment: fat-production
environment-defaults:
  fat-production:
    branch: null
    repository: null
global:
  application_name: fat
  branch: null
  default_ec2_keyname: aws-eb-eray
  default_platform: Python 3.4
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: serkansokmen@eray
  repository: null
  sc: git
  workspace_type: Application
